### PR TITLE
#41 solved show data based on user's current location

### PR DESCRIPTION
**Pull request by nik29213**
feature added by which users can search data regarding calamities in their current location.This feature has been implemented using free IP geolocation by geoplugin.

### CODE REVIEW

**Comment by swghosh** [comment]
How about using the native HTML5 Geolocation API to request user location directly from device instead of a plugin for IP based tracing? 
https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

**Comment by nik29213** [comment]
> How about using the native HTML5 Geolocation API to request user location directly from device instead of a plugin for IP based tracing?
> https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API

actually,we need to get the country's name from the user's location for dashboard i.e reverse geocoding.Although it can be implemented using google's geocoder api,but now its not free
https://developers.google.com/maps/documentation/geocoding/usage-and-billing

**Comment by swghosh** [comment]
Yep. We are not using Google Maps because of the pricing, but for the other parts of the project we've OpenStreetMap, and somewhere as well Geocoding has been implemented by use of OpenStreetMap's Nominatim Gecoding service which is also free. https://nominatim.openstreetmap.org/

**Comment by nik29213** [comment]
Yup .I considered only the country from the user's current location because in dashboard we are presenting data only on the basis of country,but other options can also be considered.
@theartist007 ,are we supposed to show data on the basis of co-ordinates?

**Comment by theartist007** [comment]
@nik29213 @swghosh , what I think should be the best possible goal for us, depending on the current architecture, is that we scrap the user's current location, and show it as accurately as possible, in the map, and show the data for that country in the past data section.
Eg : Currently, I am staying at Durgapur, West Bengal. So, if I opt for services based on my current location, then, the map should show a close enough location of mine in Durgapur, and the past data should show the data for India.

**Comment by theartist007** [comment]
Also, there should be an option for the user to opt for services, on the basis of his current location, or that entered by him manually.

**Comment by nik29213** [comment]
> Also, there should be an option for the user to opt for services, on the basis of his current location, or that entered by him manually.

yup,both the options are available

**Comment by nik29213** [comment]
> @nik29213 @swghosh , what I think should be the best possible goal for us, depending on the current architecture, is that we scrap the user's current location, and show it as accurately as possible, in the map, and show the data for that country in the past data section.
> Eg : Currently, I am staying at Durgapur, West Bengal. So, if I opt for services based on my current location, then, the map should show a close enough location of mine in Durgapur, and the past data should show the data for India(since the current data is available only on the basis of country).

sounds good.will update you with the changes

**Pull request merged**
