### PR TITLE
Login + Sign up page with CSS

### PR DESCRIPTION
**Pull request by khyati18**

### CODE REVIEW

**Comment by satyamroy001** [comment]
Why don't you use template????

**Comment by khyati18** [comment]
Actualy, never used them should it be done with templates ?

**Comment by theartist007** [comment]
@satyamroy001, I think using templates trades freedom, for ease of use. This isn't something we would recommend since the work isn't that complex.

**Comment by khyati18** [comment]
screenshot from 2018-12-26 16-43-27
screenshot from 2018-12-26 16-43-19
I have done all changes but box outside input is coming I can't understand why.
What else should I do ?

**Comment by khyati18** [comment]
Any more changes required ?

**Pull request closed without merging**
